---
apiVersion: v1
kind: Service
metadata:
  name: schema
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: schema-registry
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: "schema"
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:5.2.1
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafka-hs:9093
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: registry
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081